/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BasicSettings: typeof import('./src/components/BasicSettings.vue')['default']
    CeilButtons: typeof import('./src/components/CeilButtons.vue')['default']
    CopyrightInfo: typeof import('./src/components/CopyrightInfo.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    FloorButtons: typeof import('./src/components/FloorButtons.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsCard: typeof import('./src/components/SettingsCard.vue')['default']
    SettingsContent: typeof import('./src/components/SettingsContent.vue')['default']
    VideoItem: typeof import('./src/components/VideoItem.vue')['default']
    VideoList: typeof import('./src/components/VideoList.vue')['default']
  }
}
